# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newaccount',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
